
<?php
	session_start();
	require 'funcs/conexion.php';
	include 'funcs/funcs.php';
	
	$idUsuario = $_SESSION['id_usuario'];
	
	$sql = "SELECT id_alumno, nombre, apellido_p FROM alumnos WHERE id_alumno = '$idUsuario'";
	$result = $mysqli->query($sql);
	
  $row = $result->fetch_assoc();
  
  
?>


<!-- Inicio de Página-->
<!doctype html>
<html lang="es">
	<head>

		<title>Admin BS</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Alumnos_Ejercicios</title>
        

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
        
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
        <link rel="stylesheet" href="css/styles.css">


        <!-- scripts -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <!-- scripts google-->
        <script src='https://www.google.com/recaptcha/api.js'></script>

	</head>
	<style>
			/* Generated by Font Squirrel (http://www.fontsquirrel.com) on November 26, 2014 
			
			#cronometro { padding:10px; border: 5px #7c7bff double; width: 200px;
						text-align: center; background-color: #007; border-radius: 5px;
										float: right; margin: 1em 3em 1em 3em; }*/
			#reloj { padding: 5px 10px; width: 90% ;border: 1px solid black; 
					font: normal 1em digital_dream, europa, arial; text-align: center; 
					margin: 4px; background-color: #f0ffff; border-radius: 3px;  }
			/* #cronometro [type=button]  { margin: 4px; font: normal 9pt arial; width: 70px; } */
	</style>

	<body>
		<div class="container-fluid" style="border: 0px; margin: 0px; padding:0px">
					
					<!-- start navbar -->
					<nav class="navbar navbar-expand-lg navbar-light">
    <img src="img/C/LogoC.png" alt="">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
                <a class="nav-link" href="Alumnos.php">Alumnos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Secciones
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="Alumnos_Unidades.php">Lecciones</a>
                <a class="dropdown-item" href="Alumnos_Ejercicios.php">Ejercicios</a>
                <a class="dropdown-item" href="inicio_examen.php">Practicas</a>
                
                
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Contacto</a>
            </li>
            <li>
                <a class="nav-link" href='logout.php'>Cerrar Sesi&oacute;n</a>
            </li>
            
        </ul>
    </div>
</nav>
			<!-- end navbar -->

			<div class="jumbotron">
			</br>
				<h2 >  <?php echo ' Éxito '.$row['nombre']; ?>  </h2>
				<br />
			</div>

		
			<div class="container">	
			 <div class="row">	
			  <div id="cronometro" class="col-4">
						<div id="reloj">
						0 00 00 00
						</div>
			  </div>

					<div class="col-12">
						<form name="cron" action="cronometro.php" method="post">
							</br>
							<input type="button" value="Inicia examen" name="boton1"   />							
							</br>


								<p class="pt-4">1.¿A qué clase de tipo de datos pertenece el tipo int?<select name="1"class="selectpicker" multiple data-max-options="1"> <!--Clase para seleccionar valores-->
											<option value="1">Entero normal</option>
											<option value="0">Decimal normal</option>
											<option value="0">Ambas respuestas son correctas</option>
								</select></p>
								
								<p class="pt-4">2.Si necesitamos una variable para almacenar valores como 3.1416, ¿de qué tipo declararemos la variable?<select name="2" class="selectpicker" multiple data-max-options="1"> <!--Clase para seleccionar valores-->
											<option value="0">Char</option>
											<option value="1">Float</option>
											<option value="0">Int</option>
								</select></p> 

								<p class="pt-4">3.Se quiere declarar una variable festivo para indicar si el día actual es festivo o no lo es. ¿Cuál será el tipo más idóneo para declarla?<select name="3" class="selectpicker" multiple data-max-options="1">
											<option value="0">Char</option>
											<option value="1">Boolean</option>
											<option value="0">Float</option>
										</select></p>

								<p class="pt-4">4.Dada una variable palabra declarada como char, ¿qué sentencia será correcta?<select name="4" class="selectpicker" multiple data-max-options="1">
											<option value="0">palabra := 'b';</option>
											<option value="0">palabra := 'Beni';</option>
											<option value="1">palabra := "b";</option>
										</select>.</p>
								
								<p class="pt-4">5.Dada la declaración de constante nombre = 'valor', ¿de qué tipo es la constante?<select name="5" class="selectpicker" multiple data-max-options="1">
											<option value="0">int</option>
											<option value="0">char</option>
											<option value="1">Las constantes no son de ningún tipo </option>
										</select>.</p> 

								
							
							</br>

							<input type="button" value="Finaliza examen" name="boton2"  />  <br/>
							</br>
							<input type="submit" value="Envía Examen">
								</br>
								</br>
								</br>
							
						</form>					
			  		</div> 
			 </div>                
			</div>  
			
		
			<!-- start footer -->
			

			<script language="javascript" type="text/javascript"> 

					window.onload = function() {

					visor=document.getElementById("reloj"); //localizar pantalla del reloj
					//asociar eventos a botones: al pulsar el botón se activa su función.
					document.cron.boton1.onclick = activo; 
					document.cron.boton2.onclick = pausa; 
					document.cron.boton1.disabled=false; 
					document.cron.boton2.disabled=true; 
				
					//variables de inicio:
					var marcha=0; //control del temporizador
					var cro=0; //estado inicial del cronómetro.

					}

					//botón Empezar / Reiniciar
					function activo (){   
						if (document.cron.boton1.value=="Inicia examen") { //botón en "Empezar"
							empezar() //ir  la función empezar
							}
						else {  //Botón en "Reiniciar"
							reiniciar()  //ir a la función reiniciar
							}
						}
					//botón pausa / continuar
					function pausa (){ 
						if (marcha==0) { //con el boton en "continuar"
							 //ir a la función continuar
							}
						else {  //con el botón en "parar"
							parar() //ir a la funcion parar
							}
						}
					//Botón 1: Estado empezar: Poner en marcha el crono
					function empezar() {
						emp=new Date() //fecha inicial (en el momento de pulsar)
						elcrono=setInterval(tiempo,10); //función del temporizador.
						marcha=1 //indicamos que se ha puesto en marcha.
						//document.cron.boton1.value="Reiniciar"; //Cambiar estado del botón ahora el voton que antes decia "Empezar" dira "Reiniciar"
						document.cron.boton2.disabled=false; //activar botón de pausa
						}

					//función del temporizador			
					function tiempo() { 
						actual=new Date(); //fecha a cada instante
							//tiempo del crono (cro) = fecha instante (actual) - fecha inicial (emp)
						cro=actual-emp; //milisegundos transcurridos.
						cr=new Date(); //pasamos el num. de milisegundos a objeto fecha.
						cr.setTime(cro); 
							//obtener los distintos formatos de la fecha:
						cs=cr.getMilliseconds(); //milisegundos 
						cs=cs/10; //paso a centésimas de segundo.
						cs=Math.round(cs); //redondear las centésimas
						sg=cr.getSeconds(); //segundos 
						mn=cr.getMinutes(); //minutos 
						ho=cr.getHours()-1; //horas 
							//poner siempre 2 cifras en los números		 
						if (cs<10) {cs="0"+cs;} 
						if (sg<10) {sg="0"+sg;} 
						if (mn<10) {mn="0"+mn;} 
							//llevar resultado al visor.		 
						visor.innerHTML=" "+mn+" "+sg+" "+cs; 
						}
					//parar el cronómetro
						function parar() { 
						clearInterval(elcrono); //parar el crono
						marcha=0; //indicar que está parado.
						//document.cron.boton2.value="Continuar"; //cambiar el estado del botón
						actual=new Date(); //fecha a cada instante
								//tiempo del crono (cro) = fecha instante (actual) - fecha inicial (emp)
								cro=actual-emp; //milisegundos transcurridos.
								cr=new Date(); //pasamos el num. de milisegundos a objeto fecha.
								cr.setTime(cro); 
									//obtener los distintos formatos de la fecha:
								cs=cr.getMilliseconds(); //milisegundos 
								cs=cs/10; //paso a centésimas de segundo.

								cs=Math.round(cs); //redondear las centésimas
								sg=cr.getSeconds(); //segundos 
								mn=cr.getMinutes(); //minutos 
								ho=cr.getHours()-1; //horas 
									//poner siempre 2 cifras en los números		 
								if (cs<10) {cs="0"+cs;} 
								if (sg<10) {sg="0"+sg;} 
								if (mn<10) {mn="0"+mn;} 
									//llevar resultado al visor.		 
								document.cron.boton1.disabled=true; // desabilitamos el boton para empezar la prueba 
								//window.alert(sg);  **********************************************************************************************************
								return sg;
				
						}		 

						
				

			</script>
			
			<div class="container-fluid" style="border: 0px; margin: 0px; padding:0px">
				<?php
					require_once('footer.php');
				?>
				<!-- end footer -->
			</div>

		</div>		

	</body>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="js/jquery.slim.js"></script>
    <script src="js/popper.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/scripts.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    
</html>		